// Generated by gencpp from file my_package/mensajeTest.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_MENSAJETEST_H
#define MY_PACKAGE_MESSAGE_MENSAJETEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_package
{
template <class ContainerAllocator>
struct mensajeTest_
{
  typedef mensajeTest_<ContainerAllocator> Type;

  mensajeTest_()
    : palabra()  {
    }
  mensajeTest_(const ContainerAllocator& _alloc)
    : palabra(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _palabra_type;
  _palabra_type palabra;




  typedef boost::shared_ptr< ::my_package::mensajeTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::mensajeTest_<ContainerAllocator> const> ConstPtr;

}; // struct mensajeTest_

typedef ::my_package::mensajeTest_<std::allocator<void> > mensajeTest;

typedef boost::shared_ptr< ::my_package::mensajeTest > mensajeTestPtr;
typedef boost::shared_ptr< ::my_package::mensajeTest const> mensajeTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::mensajeTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::mensajeTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_package': ['/home/eric/catkin_ws/src/my_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_package::mensajeTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::mensajeTest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::mensajeTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::mensajeTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::mensajeTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::mensajeTest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::mensajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03b75dcc444598b70de1a710d2e07df8";
  }

  static const char* value(const ::my_package::mensajeTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03b75dcc444598b7ULL;
  static const uint64_t static_value2 = 0x0de1a710d2e07df8ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::mensajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/mensajeTest";
  }

  static const char* value(const ::my_package::mensajeTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::mensajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string palabra\n\
";
  }

  static const char* value(const ::my_package::mensajeTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::mensajeTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.palabra);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mensajeTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::mensajeTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::mensajeTest_<ContainerAllocator>& v)
  {
    s << indent << "palabra: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.palabra);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_MENSAJETEST_H
